In [4]:
import pandas as pd

# File paths
data_path = r"C:\Users\OFFICE DESK\OneDrive\Desktop\LSGD_Analysis\data.csv"
assembly_path = r"C:\Users\OFFICE DESK\OneDrive\Desktop\LSGD_Analysis\assembly_details.csv"

# Read CSVs
data_df = pd.read_csv(data_path)
assembly_df = pd.read_csv(assembly_path)

# Merge on LBCode (data) and Code (assembly)
merged_df = data_df.merge(assembly_df[['Code', 'Assembly']], 
                          left_on='LBCode', 
                          right_on='Code', 
                          how='left')

# Drop 'Code' if not needed
merged_df.drop(columns=['Code'], inplace=True)

# Save updated file (with Assembly column)
output_path = r"C:\Users\OFFICE DESK\OneDrive\Desktop\LSGD_Analysis_with_Assembly.csv"
merged_df.to_csv(output_path, index=False)

print(f"Merged file saved to: {output_path}")

Merged file saved to: C:\Users\OFFICE DESK\OneDrive\Desktop\LSGD_Analysis_with_Assembly.csv

In [5]:
data_path = r"C:\Users\OFFICE DESK\OneDrive\Desktop\LSGD_Analysis\data.csv"
data_df = pd.read_csv(data_path)


# Create VotePercentage bins (0–10%, 10–20%, …, 90–100%)
bins = range(0, 101, 10)  # [0,10,20,...100]
labels = [f"{i}-{i+10}%" for i in bins[:-1]]  # '0-10%', '10-20%', etc.

data_df['VoteBin'] = pd.cut(
    merged_df['VotePercentage'], 
    bins=bins, 
    labels=labels, 
    include_lowest=True, 
    right=False  # [0–10) instead of (0–10]
)

In [6]:
data_df.head()

,District,LBCode,LBName,WardCode,WardName,Party,Candidate,Gender,Age,Address,...,Rank,Lead,Front,Strength,LBType,Tier,WardTotalVotes,VotePercentage,Assembly,VoteBin
0,ALAPPUZHA,B04031,Thykkattussery,B04031001,Arookkutty,CPI(M),Merijanatt,M,38.0,"Kazhunnukatt, Vaduthala jetty P O, Aroorukkutty",...,2,-82,LDF,-50 to -99,Block,Block,7332,42.03,NaN,40-50%
1,ALAPPUZHA,B04031,Thykkattussery,B04031001,Arookkutty,BJP,Mini,M,47.0,"Kizhakkemaliyekkal, Arookkutty PO",...,3,-2078,NDA,-500 or less,Block,Block,7332,14.81,NaN,10-20%
2,ALAPPUZHA,B04031,Thykkattussery,B04031001,Arookkutty,INC,Animole,M,50.0,"Kavusseri,Arookkutty P O,688535",...,1,82,UDF,50-99,Block,Block,7332,43.15,NaN,40-50%
3,ALAPPUZHA,B04031,Thykkattussery,B04031002,Perumbalam,CPI(M),Sobhanakumari,M,61.0,"Manjuthara,Perumbalam P O",...,1,962,LDF,500+,Block,Block,6901,50.76,NaN,50-60%
4,ALAPPUZHA,B04031,Thykkattussery,B04031002,Perumbalam,INC,Sreerenjini,M,30.0,"Pattekkadu, Perumbalam P O , Cherthala",...,2,-962,UDF,-500 or less,Block,Block,6901,36.82,NaN,30-40%

In [7]:
pd.crosstab(data_df['Rank'], data_df['VoteBin'])

VoteBin,0-10%,10-20%,20-30%,30-40%,40-50%,50-60%,60-70%,70-80%,80-90%,90-100%
Rank,,,,,,,,,,
1,0,1,133,2673,8459,7450,2220,655,217,26
2,73,715,4855,10234,5945,0,0,0,0,0
3,7662,7216,4784,258,0,0,0,0,0,0
4,6422,1131,53,0,0,0,0,0,0,0
5,2395,64,0,0,0,0,0,0,0,0
6,727,3,0,0,0,0,0,0,0,0
7,208,0,0,0,0,0,0,0,0,0
8,55,0,0,0,0,0,0,0,0,0
9,23,0,0,0,0,0,0,0,0,0
10,6,0,0,0,0,0,0,0,0,0
11,2,0,0,0,0,0,0,0,0,0
12,1,0,0,0,0,0,0,0,0,0

In [8]:
iuml_df = data_df[data_df['Party'] == 'IUML']

# Create table of Rank vs VoteBin for IUML
pd.crosstab(iuml_df['Rank'], iuml_df['VoteBin'])

VoteBin,0-10%,10-20%,20-30%,30-40%,40-50%,50-60%,60-70%,70-80%,80-90%,90-100%
Rank,,,,,,,,,,
1,0,0,3,73,466,982,398,144,45,16
2,0,26,125,316,460,0,0,0,0,0
3,26,35,51,4,0,0,0,0,0,0
4,35,16,0,0,0,0,0,0,0,0
5,9,1,0,0,0,0,0,0,0,0
6,3,0,0,0,0,0,0,0,0,0

In [9]:
# Filter for 40–45% and 45–50%
range_40_45 = data_df[(data_df['VotePercentage'] >= 40) & (data_df['VotePercentage'] < 45)]
range_45_50 = data_df[(data_df['VotePercentage'] >= 45) & (data_df['VotePercentage'] < 50)]

# Rank distribution for each range
dist_40_45 = range_40_45['Rank'].value_counts().sort_index()
dist_45_50 = range_45_50['Rank'].value_counts().sort_index()

# Combine into a single table
rank_distribution = pd.DataFrame({
    '40-45%': dist_40_45,
    '45-50%': dist_45_50
}).fillna(0).astype(int)

In [10]:
rank_distribution

      40-45%  45-50%
Rank
1       3512    4947
2       4096    1849

In [11]:
# Define bins and labels
bins = [0, 30, 40, 50, 60, 100]   # cut points
labels = ["0-30", "30-40", "40-50", "50-60", "60+"]  # category names

# Create VoteStrength column
data_df['VoteStrength'] = pd.cut(
    data_df['VotePercentage'],
    bins=bins,
    labels=labels,
    include_lowest=True,
    right=False  # [ ) intervals: 0–30, 30–40, etc.
)

In [13]:
data_df

,District,LBCode,LBName,WardCode,WardName,Party,Candidate,Gender,Age,Address,...,Lead,Front,Strength,LBType,Tier,WardTotalVotes,VotePercentage,Assembly,VoteBin,VoteStrength
0,ALAPPUZHA,B04031,Thykkattussery,B04031001,Arookkutty,CPI(M),Merijanatt,M,38.0,"Kazhunnukatt, Vaduthala jetty P O, Aroorukkutty",...,-82,LDF,-50 to -99,Block,Block,7332,42.03,NaN,40-50%,40-50
1,ALAPPUZHA,B04031,Thykkattussery,B04031001,Arookkutty,BJP,Mini,M,47.0,"Kizhakkemaliyekkal, Arookkutty PO",...,-2078,NDA,-500 or less,Block,Block,7332,14.81,NaN,10-20%,0-30
2,ALAPPUZHA,B04031,Thykkattussery,B04031001,Arookkutty,INC,Animole,M,50.0,"Kavusseri,Arookkutty P O,688535",...,82,UDF,50-99,Block,Block,7332,43.15,NaN,40-50%,40-50
3,ALAPPUZHA,B04031,Thykkattussery,B04031002,Perumbalam,CPI(M),Sobhanakumari,M,61.0,"Manjuthara,Perumbalam P O",...,962,LDF,500+,Block,Block,6901,50.76,NaN,50-60%,50-60
4,ALAPPUZHA,B04031,Thykkattussery,B04031002,Perumbalam,INC,Sreerenjini,M,30.0,"Pattekkadu, Perumbalam P O , Cherthala",...,-962,UDF,-500 or less,Block,Block,6901,36.82,NaN,30-40%,30-40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74688,WAYANAD,M12082,Sulthanbethery,M12082034,Pazhuppathoor,INC,Mercy,M,56.0,Pedikkattukunnel,...,46,UDF,Jan-49,Municipality,Ward,882,44.90,Sulthan Batheri,40-50%,40-50
74689,WAYANAD,M12082,Sulthanbethery,M12082035,Kaivattamoola,JD(S),Rahmath,M,47.0,Illath,...,-210,LDF,-200 to -499,Municipality,Ward,1009,28.54,Sulthan Batheri,20-30%,0-30
74690,WAYANAD,M12082,Sulthanbethery,M12082035,Kaivattamoola,IND,Shaukkathali,F,41.0,Kallikkudathil,...,210,OTH,200-499,Municipality,Ward,1009,49.36,Sulthan Batheri,40-50%,40-50
74691,WAYANAD,M12082,Sulthanbethery,M12082035,Kaivattamoola,BJP,V Sheeja,M,45.0,Kunnumpurath,...,-308,NDA,-200 to -499,Municipality,Ward,1009,18.83,Sulthan Batheri,10-20%,0-30
74692,WAYANAD,M12082,Sulthanbethery,M12082035,Kaivattamoola,WPI,Abidali,F,54.0,Kozhissery,...,-465,OTH,-200 to -499,Municipality,Ward,1009,3.27,Sulthan Batheri,0-10%,0-30

In [14]:
data_df.to_csv(data_path, index=False)

In [8]:
data_path = r"C:\Users\OFFICE DESK\OneDrive\Desktop\LSGD_Analysis\data.csv"
data_df = pd.read_csv(data_path)

# Total votes polled in each assembly
total_votes = (
    data_df.groupby('Assembly')['Votes']
    .sum()
    .reset_index()
    .rename(columns={'Votes': 'TotalVotes'})
)

# Total IUML votes in each assembly
iuml_votes = (
    data_df[data_df['Party'] == 'IUML']
    .groupby('Assembly')['Votes']
    .sum()
    .reset_index()
    .rename(columns={'Votes': 'IUMLVotes'})
)

# Merge the two
assembly_votes = pd.merge(total_votes, iuml_votes, on='Assembly', how='left').fillna(0)

# Add IUML share percentage
assembly_votes['IUMLShare%'] = (assembly_votes['IUMLVotes'] / assembly_votes['TotalVotes'] * 100).round(2)

# Sort by IUMLVotes (descending)
assembly_votes = assembly_votes.sort_values(by='IUMLVotes', ascending=False)

assembly_votes.to_csv('assembly_votes.csv', index=False)

In [6]:
iuml_votes.to_csv('iuml_votes.csv', index=False)